name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
    - run: python3 -m pip install mypy
    - run: mypy svc_ttk/__init__.py

  pytest:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - run: |
          python3 -m pip install pytest
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest

  # Separate from other pytests because tkinter doesn't work on macos with actions/setup-python.
  # It imports, but gives this error:    RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
  pytest-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - run: brew install python@${{ matrix.python-version }}
    - run: |
          brew install python-tk@${{ matrix.python-version }}
          export PATH="/opt/homebrew/opt/python@${{ matrix.python-version }}/libexec/bin:$PATH"
          python3 --version
    - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install . --break-system-packages
          python3 -m pip install pytest --break-system-packages
          python3 -m pytest
